### ISSUE TITLE
Problem with Recyclerview after show message

### ISSUE THREAD

**Issue by luangs7** [fede87/StatusBarAlert#2]
Hey mate, first of all I want to say congrats to the work that you have made here.

Its a really good library, to be honest.

But I'm facing a issue that is making me really crazy.

 I'm calling the StatusBarAlert message and, after that, I call the `setAdapter` to populate my RecyclerView.

But, the onBindViewHolder its not called. Not until I scroll the empty Recycler, who is setted to "match_parent".

I tried to change the StatusBarAlert to a simple SnackBar, and it made my recycler work again.

Do you imagine what is causing this trouble with Recycleview?

**Comment by fede87** [comment]
Hi! 
Thanks for the support, I tried quickly to use Status Bar Alert within test project available here https://github.com/googlesamples/android-RecyclerView post delaying adapter setting after the alert has shown, without encountering any issue. 
Can you provide a sample code that replicates the error? Wich support lib and test devices are you currently using?

**Comment by luangs7** [comment]
Hey mate, I made another project to show you but I can't reproduced the issue. 

I think it was a logic error by myself, maybe

Sorry about that. Thanks for your time!
