### ISSUE TITLE
Issue after status bar animation ends

### ISSUE THREAD

**Issue by nightjar0** [fede87/StatusBarAlert#4]
On Android 7, after animation of staus bar ends, the status bar changes to WHITE color, not to the original status bar color

**Comment by fede87** [comment]
Hi, thanks for the report. 
I have tested with android 7 on emulator, no issue found, can  you gave me more details?
Are you providing the alert color with the function withAlertColor(color) on the builder object? 
You can achieve transparent effect providing same color used in the theme for the status bar.

**Comment by nestoleh** [comment]
Hi, I think @muhammadnomany25 meant status bar text and icons color, not the background. I have the same behavior on Android 10 (Xiaomi Mi Mix 3). Text of toolbar always white after StatusBarAlert showing and hiding, even if it was dark before and set as dark for activity theme.

**Comment by nestoleh** [comment]
I added a pull request #5 to keep UI visibility flags, that will help to keep the status bar content color, @fede87 can you please look closer at it?

**Comment by fede87** [comment]
Thanks @nestoleh for your contribution, I tried your changes but unfortunately if the alert view is shown when the status is not in low profile mode, when the alert view is going to be hidden the status bar will not reset its status to normal.
If you are looking to keep the status bar in the previous state if you show the alert view and the status bar is in low profile or immersive mode yet, the flag should be cached before showing the alert and reset after the hide animation. I will work on it in a further release.

**Comment by nestoleh** [comment]
Hi @fede87, thanks for the response. It was my bad, I tested these changes on a Xiaomi device, and looks like MIUI doesn't work correctly with low profile mode (status bar never changed in low profile). Looks like I know how to fix this, we just need to remove the "low profile" flag on alert hide. I added new pull request #6  with these changes and tested it on the real device and emulators, for me it works correctly.

**Comment by fede87** [comment]
Thanks @nestoleh again for your contribution and your quick fix! 
I've tested and merged your pull request.

**Comment by nestoleh** [comment]
Great! Are you planning a new release in the near future?

**Comment by fede87** [comment]
@nestoleh I'm going to release it today, I've also added a couple of features to change text and progress bar colors.
