### ISSUE TITLE
it doesn't show message in the activity/fragment 's onCreate or any other lifecycle method

### ISSUE THREAD

**Issue by mrYasinHamidi** [fede87/StatusBarAlert#7]
At the  start of an activity I need to show a message in the status bar , i build a StatusBarAlert object with "connecting..." message, but it doesn't show the message or progress bar 

![Screenshot from 2021-04-05 00-23-28](https://user-images.githubusercontent.com/51910690/113519982-2a7e6100-95a5-11eb-85f6-9cc793a56e7f.png)

**Comment by fede87** [comment]
Hi, thanks for your message.
I have fixed the error in this new version: 

implementation 'com.github.fede87:StatusBarAlert:1.2.1'

Would you please try with the new version?

**Comment by mrYasinHamidi** [comment]
Thank you, bro👌👌👌
That's worked.

- Also, there is some version of Android that your library does not work at all, for example : 
Huawei Y3 2017 android version 6

**Comment by fede87** [comment]
Great!Thank you for the test, I will also check the lib with android 6.

**Comment by fede87** [comment]
Hi @mrYasinHamidi ,
I have tested the lib again on emulator with api 23 (android 6) and I did not discover any error.
Is still not working on Huawei Y3 2017 android version 6 as you mentioned?
Thanks
